site_name: Object Oriented Programming
site_author: "Vu Anh"
google_analytics: ["UA-68978617-1", "magizbox.com"]

pages:
- "<span class='fa fa-home'></span> Home": "index.md"
- "Overview": "overview.md"
- "UML": "uml.md"
- "SOLID": "solid.md"
- "Design Patterns": "design_pattern.md"
- "<span class='fa fa-rss'></span> News": "feed.md"

markdown_extensions:
    - footnotes

extra_css:
  - components/magiz-c-book/src/book.css
  - components/magiz-c-course/src/course.css
  - components/magiz-c-video/src/video.css
  - components/magiz-c-benchmark/src/benchmark.css
  - components/magiz-c-paper/src/paper.css
  - components/magiz-c-feed/src/feed.css

extra_javascript:
  - components/underscore/underscore.js
  - components/magiz-c-book/src/gspreadsheet.js
  - components/magiz-c-paper/src/paper.js
  - components/magiz-c-course/src/course.js
  - components/magiz-c-benchmark/src/benchmark.js
  - components/magiz-c-benchmark/src/bootstrap-popup.js
  - components/magiz-c-book/src/book.js
  - components/magiz-c-video/src/video.js
  - components/magiz-c-feed/src/feed.js
